### ISSUE TITLE
Integration failed with HA OS 6.2

### ISSUE THREAD

**Issue by H4rl3k1n** [Bouni/luxtronik#21]
Hi,

i just installed the latest HA OS 6.2, after reboot the Integration luxtronic failed:
Unable to prepare setup for platform luxtronik.sensor: Unable to set up component.
I made some restarts (core and os), still doesnt work. All luxttonik Sensors or entities are gone.
Novelan heatpump works fine, i havent changed anything in configuration yaml.

**Comment by H4rl3k1n** [comment]
Here the complete errormessage:
benutzerdefinierte

Logger: homeassistant.setup
Source: custom_components/luxtronik/__init__.py:99
Integration: luxtronik
First occurred: 16:06:10 (1 occurrences)
Last logged: 16:06:10

Error during setup of component luxtronik
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik/__init__.py", line 72, in setup
    luxtronik = LuxtronikDevice(host, port, safe, lock_timeout)
  File "/config/custom_components/luxtronik/__init__.py", line 99, in __init__
    self._luxtronik = Lux(host, port, safe)
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 25, in __init__
    self.read()
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 38, in read
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 29, in _connect
    self._socket.connect((self._host, self._port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by Bouni** [comment]
Strange, but I guess your HA setup can, for whatever reason, not connect to the heatpump as the error `ConnectionRefusedError: [Errno 111] Connection refused` shows.
Do you have shell access to that system and can do a `telnet <ip of your heatpump> 8889`? 
That should establish a connection that gets closed by the heatpump shortly after but not showing `telnet: Unable to connect to remote host: Connection refused`

**Comment by H4rl3k1n** [comment]
well... sorry for the panic ;) the ip was given twice in my network... erm... close it pls. many thanks for the lightspeed reply, great.

**Comment by Bouni** [comment]
Happy that you figured it out (and that it wasn't the components fault 😅 )
