### ISSUE TITLE
luxtronik addon prevents homeassistant from starting

### ISSUE THREAD

**Issue by host-guru** [Bouni/luxtronik#27]
luxtronik addon is not found by homeassistant.
im running HA 2021.10.6 in docker container.

if this is a config error on my side, please tell me where i've gone wrong. i just added this to config.yml
```
luxtronik:
  host: 192.168.2.110
  port: 8889
```

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:171
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 00:29:55 (2 occurrences)
Last logged: 21:29:21

[3868706008] The system cannot restart because the configuration is not valid: Integration error: luxtronik - Integration 'luxtronik' not found.
[3869455552] The system cannot restart because the configuration is not valid: Integration error: luxtronik - Integration 'luxtronik' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 171, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Integration error: luxtronik - Integration 'luxtronik' not found.

**Comment by Bouni** [comment]
Have you installed the custom component via HACS?
Can you verify that the component is under `config/custom_components/luxtronik`?

**Comment by host-guru** [comment]
Thanks for the Info, didn't know hacs was a prerequisit.
