### ISSUE TITLE
Error during setup of component luxtronik

### ISSUE THREAD

**Issue by marcgerner** [Bouni/luxtronik#28]
Hi @Bouni,

Thanks for making this integration! It's much appreciated that you take the time to connect my device.

I've installed the custom components (upload the files) and I've done the settings in configuration.yaml. However, I keep getting this error when I start HA. I can't find the cause of this issue and I don't see anything that I'm doing wrong (although that might be the case). What the issue here?

2021-12-21 12:21:42 ERROR (MainThread) [homeassistant.setup] Error during setup of component luxtronik
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
result = await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/luxtronik/__init__.py", line 72, in setup
luxtronik = LuxtronikDevice(host, port, safe, lock_timeout)
File "/config/custom_components/luxtronik/__init__.py", line 99, in __init__
self._luxtronik = Lux(host, port, safe)
File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 25, in __init__
self.read()
File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 39, in read
self._read_parameters()
File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 66, in _read_parameters
cmd = struct.unpack(">i", self._socket.recv(4))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by hhermsen** [comment]
Hi @marcgerner, have you tried to run `pip install luxtronik`? See https://pypi.org/project/luxtronik/ It's a requirement for the use of the package

**Comment by Bouni** [comment]
It seems that the response from the heatpump is not correct: `struct.error: unpack requires a buffer of 4 bytes` 
How do you run HA (Docker, Hassio, ...)?
You can try to run this dump script and see what output you get: https://gist.github.com/Bouni/cf0dc2c7c53c32deeb264803ec350e5c

**Comment by marcgerner** [comment]
> Hi @marcgerner, have you tried to run `pip install luxtronik`? See https://pypi.org/project/luxtronik/ It's a requirement for the use of this component

I haven't installed this and I've been Googling how to run `pip install luxtronik` but I can't find how to do that... I'm not a developer, but a semi-technical IT guy that does more functional work and developes some JavaScript now and then ;-). Hope you can help me how to run such command.

I run HA OS latest version on a Raspberry Pi 3.

**Comment by Bouni** [comment]
Just to make sure, you've copied the files form [this folder](https://github.com/Bouni/luxtronik/tree/master/custom_components/luxtronik) into `config/custom_components/luxtronik/` right?

If so, HomeAssistant should install the dependencies on its own because of the [manifest.json](https://github.com/Bouni/luxtronik/blob/master/custom_components/luxtronik/manifest.json#L7-L9)

I highly recommend you to install [HACS](https://hacs.xyz/), there you can install my integration as well as several others from the GUI, you can update the custom integrations from there as well.

**Comment by marcgerner** [comment]
So after great holidays (hope you had some nice holidays as well) I continued with this issue. Previously I had HA installed with the default Raspberry PI config, but I installed it on docker now so I have more freedom of using the pi myself. 

I installed everything again and I also installed HACS and your luxtronik component, but I still get the same error as before (exact same log). I tried to run the dump script as you suggested but I get an error running the dump script. The error says: 

`Error loading script luxtronikdump.py: Line 10: "__name__" is an invalid attribute name because it starts with "_"., Line 10: "__class__" is an invalid attribute name because it starts with "_"., Line 17: "__name__" is an invalid attribute name because it starts with "_"., Line 17: "__class__" is an invalid attribute name because it starts with "_"., Line 24: "__name__" is an invalid attribute name because it starts with "_"., Line 24: "__class__" is an invalid attribute name because it starts with "_".`

I assume you think one of the sensors does not have the appropriate type or length. I can open the webpage with all sensors and check if there is a mismatch. Would that be an option?

**Comment by Bouni** [comment]
What version of python do you try to run the `luxtronikdump.py` script with?

**Comment by marcgerner** [comment]
Version is 3.9.2

**Comment by froschl2001** [comment]
Hi @Bouni,

I just ran into the same error message mentioned above.
I've slightly modified the dump_luxtronik.py to enable debugging for the library 

```
import logging

print("setting logger levels")
logger = logging.getLogger("Luxtronik")
logger.setLevel(level=logging.DEBUG)
fh = logging.StreamHandler()
fh_formatter = logging.Formatter('%(asctime)s %(levelname)s %(lineno)d:%(filename)s(%(process)d) - %(message)s')
fh.setFormatter(fh_formatter)
logger.addHandler(fh)

l = Luxtronik('192.168.0.51', 8889)

print("="*80)
print ('{:^80}'.format(' Parameters '))
print("="*80)

for n, p in l.parameters.parameters.items():
    print(f"Number: {n:<5} Name: {p.name:<60} Type: {p.__class__.__name__:<20} Value: {p.value}")

print("="*80)
print ('{:^80}'.format(' Calculations '))
print("="*80)

for n, c in l.calculations.calculations.items():
    print(f"Number: {n:<5} Name: {c.name:<60} Type: {c.__class__.__name__:<20} Value: {c.value}")

print("="*80)
print ('{:^80}'.format(' Visibilities '))
print("="*80)

for n, v in l.visibilities.visibilities.items():
    print(f"Number: {n:<5} Name: {v.name:<60} Type: {v.__class__.__name__:<20} Value: {v.value}")

```

and got the following output:

```
2022-02-17 14:35:38,252 INFO 30:__init__.py(259) - Connected to Luxtronik heatpump 192.168.0.51:8889
2022-02-17 14:35:38,277 DEBUG 67:__init__.py(259) - Command 3003
2022-02-17 14:35:38,278 DEBUG 69:__init__.py(259) - Length 1126
Traceback (most recent call last):
  File "/config/custom_components/luxtronik/dump.py", line 12, in <module>
    l = Luxtronik('192.168.0.51', 8889)
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 25, in __init__
    self.read()
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 39, in read
    self._read_parameters()
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 71, in _read_parameters
    data.append(struct.unpack(">i", self._socket.recv(4))[0])
struct.error: unpack requires a buffer of 4 bytes
```

So, Command 3003 is returning 1126 bytes, which is **not** a multiple of 4 - which explains the error.
Before I start spending time digging through your implementation without any knowledge about your code or the pump's API, I wanted to ask for any advice on how to get this resolved easily.

In case it helps, the pump is an Alpha Innotec SWCV62K3 with Software V3.85.8 (r7193).

**Comment by Bouni** [comment]
I work on a fix but it's not yet ready. I hope to get it ready in the next few days.

**Comment by Bouni** [comment]
@marcgerner Please test the latest version and let me know if that solves your problem!

**Comment by marcgerner** [comment]
Hi @Bouni,

Still the same error. I exported a file with all values that I get from the websocket api. I hope that helps.

Please find it at https://dynamics365blog.io/mail/luxtronik.xml

**Comment by Bouni** [comment]
Hey @marcgerner, 

can you post your luxtronikdump.py to a [Github Gist](https://gist.github.com) and share the link afterwards?

@froschl2001 Does the latest release fix the `struct.error: unpack requires a buffer of 4 bytes` for you?

**Comment by marcgerner** [comment]
@Bouni 

Here's the script: I don't need the import logger as that works oob. https://gist.github.com/marcgerner/d82e1b01793f0551f108c147e435a666

The error I get in the logging is:
2022-04-18 18:56:47 ERROR (SyncWorker_1) [homeassistant.components.python_script] Error loading script luxtronikdump.py: Line 16: "__class__" is an invalid attribute name because it starts with "_"., Line 23: "__class__" is an invalid attribute name because it starts with "_"., Line 30: "__class__" is an invalid attribute name because it starts with "_".

I've also tried to remove the leading __ with the attribute names, but I get another error then:
2022-04-18 18:59:31 ERROR (SyncWorker_0) [homeassistant.components.python_script.luxtronikdump.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
    exec(compiled.code, restricted_globals)
  File "luxtronikdump.py", line 2, in <module>
TypeError: 'NoneType' object is not callable

**Comment by marcgerner** [comment]
@Bouni have you been able to figure out the cause of this issue?

**Comment by marcgerner** [comment]
Hi @Bouni I did, but I still get the same error. Please find the screenshot attached down here:
![image](https://user-images.githubusercontent.com/39795870/180470327-ea3d4432-5fd9-4df5-aa07-a4655f7f403a.png)
