### ISSUE TITLE
No Adapter Connect 

### ISSUE THREAD

**Issue by kmidt** [Bouni/luxtronik#32]
Hi, everyone. I'm just switching from FHEM and IObroker to Hass.io. I was always used to using port 8888 and a password. I can't get a connection to Luxtronik with the small part in the Yaml file and the installation. Is there another trick ?

**Comment by kmidt** [comment]
Hi Thanks for the fast Answer 👍 

The Adapter is Installed : 

![image](https://user-images.githubusercontent.com/48753049/152366332-0b8b7207-2819-4d99-8724-11941a5c03c1.png)

Configuration.yaml 👍 
luxtronik:
host: “192.168.178.115”
port: 8888
scan_interval: 60


I can ping the IP

**Comment by kmidt** [comment]
by the way ; at FHEM and iobroker i musst use the standart PW from Luxtronik : 999999

But here i cant use them

**Comment by Bouni** [comment]
No password needed here. We directly access the heatpump service running on port 8888/8889.

What platform do you run HA on? 
Docker container? Hass OS? Supervised?

Because pinging the heatpump from your PC does not mean that you're able to ping it from within the HA container!

**Comment by kmidt** [comment]
I have an VM in proxmox .Inhaber Ping feom VM Hass to The headpump. Iam Admin in Hass. Is The configuration.yaml OK ? 

OK with The Password . Without a PW in fhem and iob was it Not possible

**Comment by kmidt** [comment]
Thats The Error Log :

Logger: aiohttp.server
Source: components/hassio/__init__.py:609
First occurred: 15:48:50 (3 occurrences)
Last logged: 16:04:46

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 331, in post
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 609, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Integration error: host - Integration 'host' not found.
Invalid config for [luxtronik]: required key not provided @ data['luxtronik']['host']. Got None. (See ?, line ?). 
Integration error: scan_interval - Integration 'scan_interval' not found.
Integration error: port - Integration 'port' not found.

**Comment by kmidt** [comment]
Issue solved . It works. I forgott to implements any Sensor definition. Thank you
