### ISSUE TITLE
Luxtronik not loading since last HA update

### ISSUE THREAD

**Issue by yvansandoz** [Bouni/luxtronik#67]
Here my log:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/luxtronik/__init__.py:101 
Integration: luxtronik 
First occurred: 8:49:35 PM (1 occurrences) 
Last logged: 8:49:35 PM

Error during setup of component luxtronik
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik/__init__.py", line 74, in setup
    luxtronik = LuxtronikDevice(host, port, safe, lock_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/luxtronik/__init__.py", line 101, in __init__
    self._luxtronik = Lux(host, port, safe)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/luxtronik/__init__.py", line 25, in __init__
    self.read()
  File "/usr/local/lib/python3.11/site-packages/luxtronik/__init__.py", line 40, in read
    self._connect()
  File "/usr/local/lib/python3.11/site-packages/luxtronik/__init__.py", line 29, in _connect
    self._socket.connect((self._host, self._port))
OSError: [Errno 113] Host is unreachable

**Comment by kbabioch** [comment]
>  OSError: [Errno 113] Host is unreachable

Can you verify that the host is reachable, or is there some other (network related) changes that could have caused this?

**Comment by yvansandoz** [comment]
Yes, sorry for my request, the problem was linked to a change of IP address on my router side.
You can close the case.
